version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  api:
    container_name: api
    build: ./api
    ports:
      - 5280:5280
    restart: on-failure
    depends_on:
      - rabbitmq
  web:
    container_name: web
    build: ./front
    ports:
      - 4200:80
